### ISSUE TITLE
FlexOTube Missing Texture File

### ISSUE THREAD

**Issue by deertan** [UmbraSpaceIndustries/UmbraSpaceIndustries#1]
Hey Roverdude,

When I drag a FlexOTube from a KIS container and drop it on the ground I get an error about a missing texture.

Error is: Texture File : UmbraSpaceIndustries/UKS/Assets/FlexOTube has not been found, please check your KAS installation.

I uninstalled and re-installed KAS, no fix.  Checked the path mentioned in the error, path itself does not exist.

![screenshot 2016-10-19 20 51 17](https://cloud.githubusercontent.com/assets/22947924/19542800/8f126e78-963f-11e6-9747-f3f8b353be1a.png)

**Comment by BobPalmer** [comment]
Should be sorted
