### ISSUE TITLE
New resources not showing in WOLF's main GUI

### ISSUE THREAD

**Issue by rlangeoi** [UmbraSpaceIndustries/UmbraSpaceIndustries#14]
These 5 resources are available in WOLF but are not visible in the main GUI when you try to review your depot's resource availability. These need to be added to WOLF.cfg, probably in the AssembledResourcesFilter 

Alloys,Synthetics,Robotics,Electronics,Prototypes

**Comment by tjdeckard** [comment]
Good catch! This will be updated in my next PR.
