### ISSUE TITLE
Constellation 2021.03.12.01 PRE-RELASE doesn't include 000_AT_Utils

### ISSUE THREAD

**Issue by MaraRinn** [UmbraSpaceIndustries/UmbraSpaceIndustries#16]
Symptoms:

- USI flags are available
- rover parts group exists, no rover parts are visible
- WOLF parts group exists, no WOLF parts are visible
- Constellation_2021.03.12.01.zip doesn't contain the 000_AT_Utils folder

Workaround:

 - Download the various files and assemble the 000_AT_Utils folder manually

Outcome: USI stuff including WOLF behaves as expected (so far): WOLF button is visible on action bar in SPF and VAB, parts are in the relevant part groups

**Comment by MaraRinn** [comment]
No, my problem is deeper than 000_AT_Utils. If I take ModuleManager.4.1.4.dll out, all the parts work on saved craft (so a vessel with WOLF Cargo containers can load, the route planner will complain that I need a starting depot, and the WOLF planner is available in the SPH/VAB … but the various USI parts groups do not show up: no WOLF parts, no rover parts.

If I put ModuleManager.4.1.4.dll back in, the parts groups do show up, but they have no parts and craft made with USI Constellation parts will not load due to missing parts.

**Comment by MaraRinn** [comment]
Scratch that last bit, it's just me: I created a career game instead of a sandbox game.

But if 000_AT_Utils is intended to be included in the Constellation download, this issue still stands.

**Comment by tjdeckard** [comment]
The 000_AT_Utils folder is a dependency of the Global Construction mod which we are no longer bundling with the USI suite.
