### ISSUE TITLE
USI Constellation Pre-Release Crashes

### ISSUE THREAD

**Issue by MrKiel** [UmbraSpaceIndustries/UmbraSpaceIndustries#17]
[USI Constellation Crashes.txt](https://github.com/UmbraSpaceIndustries/UmbraSpaceIndustries/files/6783352/USI.Constellation.Crashes.txt)

WOLF-Specific crashes at WOLF.WOLF_CrewTransferScenario.OnAwake and WOLF.WOLF_CrewTransferScenario.OnDestroy. 

Haven't even started using WOLF in this save yet.

**Comment by MrKiel** [comment]
[Player.log](https://github.com/UmbraSpaceIndustries/UmbraSpaceIndustries/files/6784188/Player.log)

**Comment by tjdeckard** [comment]
This has been fixed in the latest pre-release and will be available in the next stable release.
