### ISSUE TITLE
Problem with WOLF Flight Recorder and Connector

### ISSUE THREAD

**Issue by higginsmr58** [UmbraSpaceIndustries/UmbraSpaceIndustries#18]
Not seeing the flight recorder in VAB or in tech tree. Connector is showing but name seems to be linked improperly.

**Comment by higginsmr58** [comment]
Ok, think I found the problem with the flight recorder...in the WOLF_CTT.cfg file, changed:

@PART[WOLF_Transporter]:NEEDS[CommunityTechTree]
{
	@TechRequired = advlogistics
}

to:

@PART[WOLF_Transporter]:NEEDS[CommunityTechTree]
{
	@TechRequired = advLogistics
}

Now have the Flight Recorder in both the tech tree and the VAB part list. 

Haven't found any reason for the incorrect Connector name, shows as #autoLOC_USI_WOLF_CONNECTOR_PART_TITLE and description as #autoLOC_USI_WOLF_CONNECTOR_PART_DESCRIPTION in the ConnectorModule.cfg file

**Comment by higginsmr58** [comment]
And, appears to me that the name and description are just missing from the en-us.cfg localization file.

**Comment by tjdeckard** [comment]
It looks like these issues were fixed at some point. Too lazy to look up the exact commit. Closing this issue for now.
