### ISSUE TITLE
Problems with a toolbar buttons

### ISSUE THREAD

**Issue by JohnMillimetron** [UmbraSpaceIndustries/UmbraSpaceIndustries#19]
USI toolbar buttons duplicates each time the scene changes. Also buttons don't work in flight, only in KSC.
I play KSP version 1.12.2, with USI constellation Unstable Release 112.0.0.
![изображение](https://user-images.githubusercontent.com/72683464/131469104-61d92d31-04f9-4006-a8f4-e06d286bf884.png)

My GameData folder: 
![изображение](https://user-images.githubusercontent.com/72683464/131470940-505049f9-8005-4306-b3b4-e7491539ddd0.png)

Logs:
[KSP.log](https://github.com/UmbraSpaceIndustries/UmbraSpaceIndustries/files/7082440/KSP.log)
[Player.log](https://github.com/UmbraSpaceIndustries/UmbraSpaceIndustries/files/7082446/Player.log)

**Comment by tjdeckard** [comment]
This is normally a result of having multiple copies of the USI DLLs inside your GameData folder. I see a folder named GameData inside your GameData folder. I suspect that's the culprit.
