### ISSUE TITLE
Origin depot needs an additional ({0}) ColonySupplies to support this route

### ISSUE THREAD

**Issue by MaraRinn** [UmbraSpaceIndustries/UmbraSpaceIndustries#22]
I'm not sure how many ColonySupplies are needed. Setup is pretty straightforward: WOLF depot near the launchpad, rocket with Crew Cargo Kontainer on the launchpad, tried to connect to origin depot and got this message.

USI bleeding edge 2.

![Screenshot 2021-10-26 142909](https://user-images.githubusercontent.com/43090/138804309-1f318224-4a69-4fab-b71a-1a90dd0d9391.jpg)

**Comment by tjdeckard** [comment]
Will be fixed in the next release.
