### ISSUE TITLE
ISRU_Experiment can't be clicked in the VAB

### ISSUE THREAD

**Issue by Forgilageord** [UmbraSpaceIndustries/UmbraSpaceIndustries#9]
Once I let go of the ISRU_Experiment after selecting it from the parts list, I can't left or right click on it, leaving it permanently stuck wherever I left it, whether that's on a vessel or in a ghost state floating in the VAB.

**Comment by tjdeckard** [comment]
This has been fixed in the latest pre-release and will be available in the next stable release.
